# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
# Fabric Properties
# check these on https://fabricmc.net/develop/
minecraft_version=26.2
loader_version=0.19.3
java_version=25
carpet_version=26.2+v260616
# Mod Properties
mod_version=1.0-SNAPSHOT
maven_group=world.incest
archives_base_name=carpet-permissions
# Dependencies
# check this on https://fabricmc.net/develop/
fabric_version=0.154.0+26.2
fabric_permissions_api_version=0.7.0
